### ISSUE TITLE
Light treatment - Light Baking

### ISSUE THREAD

**Issue by HeluPeter** [GreenZe/SE04-NHOM-18.01#10]
Xử lý ánh sáng trong game

**Comment by DTHNhung** [comment]
lỗi nhiều quá

**Comment by nguyenminhthe-dev** [comment]
cấu hình máy k đủ dễ đơ

**Comment by longhv19** [comment]
Mình sử dụng 2 nguồn sáng cạnh nhau nhưng nó lại hiện lên dấu X, không biết là do lỗi gì :((((

**Comment by wai292000** [comment]
@Orchids-Programe mình cũng chưa thử nhưng mình nghĩ dùng 2 nguồn sáng mình nghĩ sê hay đấy hợp với thục tế nhưng mình cứ thử trước với 1 nguồn đi
