### ISSUE TITLE
Export file .exe

### ISSUE THREAD

**Issue by DTHNhung** [GreenZe/SE04-NHOM-18.01#11]
Xuất ra các file exe để tạo file game .

**Comment by DTHNhung** [comment]
Các bạn có ai gặp lỗi không, mình chưa xuất được file do lỗi C++ .

**Comment by DTHNhung** [comment]
Lỗi gặp phải là do chưa liên kết vs 2019 với UE4.

**Comment by HeluPeter** [comment]
Chụp màn hình rồi push lên đây xem nào(để ảnh trên drive), để mọi người tìm cách sửa :))

**Comment by DTHNhung** [comment]
[https://drive.google.com/file/d/1P8bb9owbZE9ATqo7jWIMiVBTo4xfYnVm/view?usp=sharing](url)
các bạn xem lỗi này nhé

**Comment by DTHNhung** [comment]
Đã fix được lỗi rồi, install vs 2019 thôi

**Comment by DTHNhung** [comment]
[https://drive.google.com/file/d/19wauQKNZR6M912jyQysTh81GTQAcfK9-/view?fbclid=IwAR25j7UKjzrYKk7PvSrI6ETc8hIj-pec9k_4Jgkn2t4-cC6bAQqJ6dQ9VN8](url)

**Comment by wai29** [comment]
sửa với đã xuất được file .exe với dữ liệu nhung gửi rồi nhé
