### ISSUE TITLE
Connection with VR

### ISSUE THREAD

**Issue by DTHNhung** [GreenZe/SE04-NHOM-18.01#12]
- Xử lý vấn đề liên kết với kính VR

**Comment by longhv19** [comment]
Các bạn đã kết nối được chưa? Mình chưa kết nối được

**Comment by wai292000** [comment]
mình đã sử dụng tương tác được với vật liệu qua máy nhưng không biết làm như thế nào để tương qua kính vr như thế nào

**Comment by wai292000** [comment]
còn kết nối với kính vr mình cũng chưa thử được

**Comment by wai292000** [comment]
ai đó chia sẻ tài liệu được không mình tìm youtube hướng dẫn người ta mình ko hiểu lắm

**Comment by DTHNhung** [comment]
@wai292000 Tương tác được rồi á, bên mình đang gặp lỗi về góc nhìn... game chạy cứ bị đi xuống lòng đất, không hiểu lắm

**Comment by wai292000** [comment]
@BouBou2k game chạy xuống lòng đất là như thế nào nhỉ do góc nhìn của bạn chăng

**Comment by DTHNhung** [comment]
lỗi rơi tự do là do chưa điều chỉnh collision

**Comment by DTHNhung** [comment]
nhánh chuột vào nền nhà, điều chỉnh và check trong mesh là okkk rồi

**Comment by nguyenminhthe-dev** [comment]
ánh sáng khá ổn rồi đấy nhỉ
