### ISSUE TITLE
FBX with the right space

### ISSUE THREAD

**Issue by DTHNhung** [GreenZe/SE04-NHOM-18.01#13]
##Tìm kiếm các file .fbx có dung lượng phù hợp để tạo game .
-  File này có dung lượng <1GB
-  Nội thất 1 tầng ( có thể là nhà ở hoặc cafe)
-  Đã được xử lý ánh sáng qua các công cụ hỗ trợ khác
-  Kiểm tra các lỗi có thể tồn tại

**Comment by DTHNhung** [comment]
Chúng mình thử với file Trường học nhé.

**Comment by wai292000** [comment]
file này không hiển thị vật liệu chắc lỗi gì r thử lại với file trường học trên nhóm chat ok hơn đấy

**Comment by DTHNhung** [comment]
okkk, sử dụng file school nhé
