### ISSUE TITLE
Download Epic Games and install Unreal Engine 4

### ISSUE THREAD

**Issue by HeluPeter** [GreenZe/SE04-NHOM-18.01#2]
**Download Epic Games and install Unreal Engine 4**
_Link download: https://www.unrealengine.com/en-US/download/ue_games_
_Link guide: https://www.youtube.com/watch?v=C__soqGoHqk_

**Comment by longhv19** [comment]
Đã cài thành công UE4!!!

**Comment by HeluPeter** [comment]
> Đã cài thành công UE4!!!
Done!

**Comment by nguyenminhthe-dev** [comment]
Đã cài thành công UE4!!!

**Comment by HeluPeter** [comment]
> Đã cài thành công UE4!!!

Ok, done!

**Comment by DamThiHongNhung** [comment]
RAM của tui có 4GB thì có tải được không?

**Comment by HeluPeter** [comment]
> RAM của tui có 4GB thì có tải được không?

Tải được nhưng lúc chạy thì chắc là sẽ bị giật lag. Nhung nên nâng cấp thêm RAM nhé!

**Comment by wai292000** [comment]
Đã cài đặt thành công UE4

**Comment by HeluPeter** [comment]
> Đã cài đặt thành công UE4

Ok, done!
