### ISSUE TITLE
Create a new branch, first commit and push your introduce.txt file

### ISSUE THREAD

**Issue by HeluPeter** [GreenZe/SE04-NHOM-18.01#3]
1. Mỗi thành viên trong nhóm tự tạo một branch mới với tên của mình (vd: nguyenvanninh)
2. Tạo một file introduce.txt gồm các thông tin:
- Họ tên & MSV
- Tên lớp + khoa
3. Tạo commit đầu tiên(vd: ninh first commit) và push file introduce.txt d lên branch của mình!

`Comment lại các bước, các câu lệnh đã thực hiện bên dưới`

**Comment by wai292000** [comment]
Đã cài thành công
