### ISSUE TITLE
Create a simple project with UE4

### ISSUE THREAD

**Issue by HeluPeter** [GreenZe/SE04-NHOM-18.01#5]
- [x] create a project on UE4 and run it

- [x] check for errors

- [x]  necessary libraries

**Comment by DTHNhung** [comment]
Đã tạo thành công cùng với việc import file thầy gửi

**Comment by HeluPeter** [comment]
Import vào rồi, nhưng nó có cái dòng đỏ đỏ là sao mọi người nhỉ?

**Comment by DTHNhung** [comment]
Báo cáo một số vật liệu không thể nhận dạng thì phải

**Comment by HeluPeter** [comment]
Thế thì có cách nào để điều chỉnh vật liệu theo ý muốn của mình không nhỉ?
