### ISSUE TITLE
Import an existing project from Markeplace and test it

### ISSUE THREAD

**Issue by HeluPeter** [GreenZe/SE04-NHOM-18.01#6]
Import an existing project from Markeplace and test it ^^

**Comment by DTHNhung** [comment]
Là sao bạn ơi?

**Comment by HeluPeter** [comment]
Bạn vào mục Market để tải 1 thư viện bất kì về và thử import vào xem có chạy được không rồi báo cáo!

**Comment by DTHNhung** [comment]
ok rồi nhá, nhưng mấy cái trên market nặng quá
