### ISSUE TITLE
Import Classroom file to UE4

### ISSUE THREAD

**Issue by wai29** [GreenZe/SE04-NHOM-18.01#7]
Import classroom file to ue4

**Comment by HeluPeter** [comment]
Đã ai thử import chưa, mình vẫn chưa biết các import?

**Comment by DTHNhung** [comment]
mình tìm hiểu thì thấy muốn import file blender vào thì trước tiên ta export ra FBX rồi mới import vào UE4

**Comment by HeluPeter** [comment]
Nhưng export ra FBX rồi sao nữa, cũng chưa thấy cách import vào UE4 sau đó?

**Comment by DTHNhung** [comment]
Cứ import như bình thường thôi, vào File >> Import

**Comment by HeluPeter** [comment]
Vào File -> Import -> Chọn Level, sau đó chọn file import và điều chỉnh các options

**Comment by wai29** [comment]
import thành công nhưng file .blend là dùng để làm gì vậy

**Comment by longhv19** [comment]
Đã import thành công!!!

**Comment by DTHNhung** [comment]
> import thành công nhưng file .blend là dùng để làm gì vậy

file .blend là file blender đó, file này không thể import trực tiếp vào UE4 nên phải chuyển thành file .fbx

**Comment by HeluPeter** [comment]
Chuyển như nào, hay download về đã có sẵn định dạng .fbx, hình như là .obj hay .ma cũng được sao ấy?

**Comment by DTHNhung** [comment]
thành công, đóng issues thôi
