### ISSUE TITLE
UE4 Material Editor - Shader Creation 

### ISSUE THREAD

**Issue by DTHNhung** [GreenZe/SE04-NHOM-18.01#8]
Sau khi import các file .fbx vào UE4, ta cần chỉnh sửa một số lỗi và áp vật liệu.
>> Comment một số lỗi khi import file .

**Comment by HeluPeter** [comment]
Kiểu như file classroom ấy, lúc import vào thì bàn ghế đều bị "gãy" hoặc không đồng đều :((

**Comment by DTHNhung** [comment]
Thường thì khi import, các file dễ gặp lỗi lắm, có khi là mất vật liệu cơ... nên phải chỉnh lại

**Comment by wai29** [comment]
hơi nặng và nhiều file máy không thể load được cũng không thể lưu
